# Week 1: Data Cleaning and Feature Engineering Report
**Intern:** Noor-ul-Ain 
**Date:** 19-Jan-2026

## AI Powered Data Analysis Remote Internship

This notebook documents the data cleaning and preparation process carried out as part of the AI-Powered Data Analysis Remote Internship. The objective of this analysis was to assess data quality, identify inconsistencies, and apply structured cleaning techniques to ensure the dataset is reliable and ready for analysis.

## Introduction
- **Purpose:** Data cleaning, Feature engineering.  
- **Data Description:** Overview of dataset: Has 8558 rows × 16 columns

In [1]:
import pandas as pd

In [3]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\user\desktop\sample_project_1\env\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\user\desktop\sample_project_1\env\lib\site-packages (from openpyxl) (2.0.0)

## Data Loading

This step loads the opportunity dataset from an Excel file into a pandas DataFrame.
The dataset is then displayed to verify that it has been imported correctly and to get an initial overview of the data structure.

In [25]:
df =pd.read_excel('SLU Opportunity Wise Data-1710158595043.xlsx')
df

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,2001-12-01 00:00:00,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,06/14/2023 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,08/16/2000,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,01/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,"45235 days, 0:21:29",2022-03-11 18:30:39
3,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,1999-01-11 00:00:00,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,04/19/2000,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Selam,10/14/2006,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,2024-11-03 12:03:14,Team Allocated,1070,2024-05-03 17:10:41,2024-08-03 14:00:00
8554,2024-06-03 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Gowri Sailesh,05/18/1999,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-06-03 18:22:11,2024-08-03 14:00:00
8555,02/29/2024 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Abiola,03/16/1999,Male,Nigeria,Tai Solarin university of Education,Political Science,2024-11-03 12:03:14,Team Allocated,1070,02/29/2024 15:10:06,2024-08-03 14:00:00
8556,12/23/2023 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,venumadhavi,1997-05-06 00:00:00,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,02/27/2024 06:48:47,2024-08-03 14:00:00
8557,2023-01-06 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Prashanth Reddy,11/30/2000,Male,India,Saint Louis University,Artificial Intelligence,2024-11-03 12:03:14,Team Allocated,1070,02/16/2024 16:33:00,2024-08-03 14:00:00

## Data Cleaning Process
- Handling missing values
- Removing duplicates
- Correcting data types
- Any issues encountered and resolutions

In [26]:
df.shape

(8558, 16)

In [27]:
df.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              5
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
dtype: int64

In [28]:
# To get information about this dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8558 entries, 0 to 8557
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Learner SignUp DateTime  8558 non-null   object
 1   Opportunity Id           8558 non-null   object
 2   Opportunity Name         8558 non-null   object
 3   Opportunity Category     8558 non-null   object
 4   Opportunity End Date     8558 non-null   object
 5   First Name               8558 non-null   object
 6   Date of Birth            8558 non-null   object
 7   Gender                   8558 non-null   object
 8   Country                  8558 non-null   object
 9   Institution Name         8553 non-null   object
 10  Current/Intended Major   8553 non-null   object
 11  Entry created at         8558 non-null   datetime64[ns]
 12  Status Description       8558 non-null   object
 13  Status Code              8558 non-null   int64
 14  Apply Date               8558 non-null   object
 15  Opportunity Start Date   4764 non-null   object
dtypes: datetime64[ns](1), int64(1), object(14)
memory usage: 1.0+ MB

In [29]:
df.columns

Index(['Learner SignUp DateTime', 'Opportunity Id', 'Opportunity Name',
       'Opportunity Category', 'Opportunity End Date', 'First Name',
       'Date of Birth', 'Gender', 'Country', 'Institution Name',
       'Current/Intended Major', 'Entry created at', 'Status Description',
       'Status Code', 'Apply Date', 'Opportunity Start Date'],
      dtype='object')

In [30]:
# To check for duplicates
df.duplicated().sum()

0

In [31]:
df[['Learner SignUp DateTime','Opportunity End Date','Date of Birth','Entry created at','Apply Date','Opportunity Start Date']]

,Learner SignUp DateTime,Opportunity End Date,Date of Birth,Entry created at,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,06/29/2024 18:52:39,2001-12-01 00:00:00,2024-11-03 12:01:41,06/14/2023 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,06/29/2024 18:52:39,08/16/2000,2024-11-03 12:01:41,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-09-04 20:35:08,06/29/2024 18:52:39,01/27/2002,2024-11-03 12:01:41,"45235 days, 0:21:29",2022-03-11 18:30:39
3,08/29/2023 05:20:03,06/29/2024 18:52:39,1999-01-11 00:00:00,2024-11-03 12:01:41,2023-09-10 22:02:42,2022-03-11 18:30:39
4,2023-06-01 15:26:36,06/29/2024 18:52:39,04/19/2000,2024-11-03 12:01:41,2023-06-01 15:40:10,2022-03-11 18:30:39
...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,2024-08-03 11:30:00,10/14/2006,2024-11-03 12:03:14,2024-05-03 17:10:41,2024-08-03 14:00:00
8554,2024-06-03 15:58:47,2024-08-03 11:30:00,05/18/1999,2024-11-03 12:03:14,2024-06-03 18:22:11,2024-08-03 14:00:00
8555,02/29/2024 15:02:31,2024-08-03 11:30:00,03/16/1999,2024-11-03 12:03:14,02/29/2024 15:10:06,2024-08-03 14:00:00
8556,12/23/2023 03:53:12,2024-08-03 11:30:00,1997-05-06 00:00:00,2024-11-03 12:03:14,02/27/2024 06:48:47,2024-08-03 14:00:00
8557,2023-01-06 13:22:01,2024-08-03 11:30:00,11/30/2000,2024-11-03 12:03:14,02/16/2024 16:33:00,2024-08-03 14:00:00

 ## Converting each datetime column to its standard format

In [32]:
col=df[['Learner SignUp DateTime','Opportunity End Date','Date of Birth','Entry created at','Apply Date','Opportunity Start Date']]

for y in col:
  df[y]=pd.to_datetime(df[y],errors='coerce')

In [33]:
df[['Learner SignUp DateTime','Opportunity End Date','Date of Birth','Entry created at','Apply Date','Opportunity Start Date']]

,Learner SignUp DateTime,Opportunity End Date,Date of Birth,Entry created at,Apply Date,Opportunity Start Date
0,2023-06-14 12:30:35,2024-06-29 18:52:39,2001-12-01,2024-11-03 12:01:41,2023-06-14 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,2024-06-29 18:52:39,2000-08-16,2024-11-03 12:01:41,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-09-04 20:35:08,2024-06-29 18:52:39,2002-01-27,2024-11-03 12:01:41,NaT,2022-03-11 18:30:39
3,2023-08-29 05:20:03,2024-06-29 18:52:39,1999-01-11,2024-11-03 12:01:41,2023-09-10 22:02:42,2022-03-11 18:30:39
4,2023-06-01 15:26:36,2024-06-29 18:52:39,2000-04-19,2024-11-03 12:01:41,2023-06-01 15:40:10,2022-03-11 18:30:39
...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,2024-08-03 11:30:00,2006-10-14,2024-11-03 12:03:14,2024-05-03 17:10:41,2024-08-03 14:00:00
8554,2024-06-03 15:58:47,2024-08-03 11:30:00,1999-05-18,2024-11-03 12:03:14,2024-06-03 18:22:11,2024-08-03 14:00:00
8555,2024-02-29 15:02:31,2024-08-03 11:30:00,1999-03-16,2024-11-03 12:03:14,2024-02-29 15:10:06,2024-08-03 14:00:00
8556,2023-12-23 03:53:12,2024-08-03 11:30:00,1997-05-06,2024-11-03 12:03:14,2024-02-27 06:48:47,2024-08-03 14:00:00
8557,2023-01-06 13:22:01,2024-08-03 11:30:00,2000-11-30,2024-11-03 12:03:14,2024-02-16 16:33:00,2024-08-03 14:00:00

## Checking for null values

In [34]:
df.isnull().sum()

Learner SignUp DateTime     295
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1262
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              5
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                  307
Opportunity Start Date     4637
dtype: int64

In [35]:
df[['Gender','Opportunity Category','Opportunity Name','Opportunity Id',
      'Institution Name','Country','Status Description',
       'Status Code']]

,Gender,Opportunity Category,Opportunity Name,Opportunity Id,Institution Name,Country,Status Description,Status Code
0,Female,Course,Career Essentials: Getting Started with Your P...,00000000-0GN2-A0AY-7XK8-C5FZPP,Nwihs,Pakistan,Started,1080
1,Female,Course,Career Essentials: Getting Started with Your P...,00000000-0GN2-A0AY-7XK8-C5FZPP,SAINT LOUIS,India,Started,1080
2,Male,Course,Career Essentials: Getting Started with Your P...,00000000-0GN2-A0AY-7XK8-C5FZPP,Illinois Institute of Technology,United States,Started,1080
3,Female,Course,Career Essentials: Getting Started with Your P...,00000000-0GN2-A0AY-7XK8-C5FZPP,Saint Louis University,United States,Team Allocated,1070
4,Male,Course,Career Essentials: Getting Started with Your P...,00000000-0GN2-A0AY-7XK8-C5FZPP,Saint Louis University,United States,Started,1080
...,...,...,...,...,...,...,...,...
8553,Female,Event,Freelance Mastery workshop,00000000-10GQ-RJHT-3G4S-BKGBY1,Lideta Catholic Cathedral School,Ethiopia,Team Allocated,1070
8554,Male,Event,Freelance Mastery workshop,00000000-10GQ-RJHT-3G4S-BKGBY1,SAINT LOUIS UNIVERSITY,United States,Team Allocated,1070
8555,Male,Event,Freelance Mastery workshop,00000000-10GQ-RJHT-3G4S-BKGBY1,Tai Solarin university of Education,Nigeria,Team Allocated,1070
8556,Female,Event,Freelance Mastery workshop,00000000-10GQ-RJHT-3G4S-BKGBY1,Saint Louis University,United States,Team Allocated,1070
8557,Male,Event,Freelance Mastery workshop,00000000-10GQ-RJHT-3G4S-BKGBY1,Saint Louis University,India,Team Allocated,1070

In [36]:
df['Gender'].unique()

array(['Female', 'Male', "Don't want to specify", 'Other'], dtype=object)

In [37]:
df['Gender'].value_counts()

Gender
Male                     5018
Female                   3522
Don't want to specify      15
Other                       3
Name: count, dtype: int64

In [38]:
df = df[df['Gender'].isin(['Male', 'Female'])]
df['Gender'].value_counts()

Gender
Male      5018
Female    3522
Name: count, dtype: int64

In [39]:
df['Opportunity Category'].value_counts()
df['Status Code'].value_counts()
df['Current/Intended Major'].value_counts()

Current/Intended Major
Information Systems             2158
Computer Science                1051
Health Data Science              371
Cyber Security                   326
Computer Information Systems     250
                                ...
AVIATION ADMINISTRATION            1
General Arts                       1
Computing                          1
Diploma                            1
Pos Service                        1
Name: count, Length: 404, dtype: int64

In [40]:
df.isnull().sum()

Learner SignUp DateTime     295
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1259
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              5
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                  307
Opportunity Start Date     4633
dtype: int64

In [41]:
# Checking null values where we have both columns side by side
missing_value=df['Institution Name'].isnull() | df['Current/Intended Major'].isnull()
df[missing_value]

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
239,2024-09-01 03:21:24,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Kavitha,2001-10-25,Female,India,NaN,Cloud Computing,2024-11-03 12:01:43,Team Allocated,1070,2024-11-01 12:15:48,2022-03-11 18:30:39
1256,2023-06-15 17:29:54,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,BIG,1998-11-15,Male,Pakistan,allama iqbal open universty,NaN,2024-11-03 12:01:54,Started,1080,2023-06-15 17:47:21,2022-03-11 18:30:39
1651,2024-02-27 13:43:42,00000000-0GNT-FT74-MZT8-93VC0G,Digital Marketing,Internship,2024-11-03 18:00:00,Sierra,2003-02-21,Female,United States,Camdenton highschool,NaN,2024-11-03 12:01:59,Rejected,1030,2024-02-27 14:03:34,NaT
1746,2023-11-24 11:18:07,00000000-0GNT-FT74-MZT8-93VC0G,Digital Marketing,Internship,2024-11-03 18:00:00,Lovertt,1995-04-26,Female,Ghana,NaN,Digital Marketing,2024-11-03 12:02:00,Team Allocated,1070,2023-11-24 11:37:01,2024-08-01 03:30:46
3347,2024-09-01 03:21:24,00000000-0GHB-4N83-QX9K-JM48K2,Project Management,Internship,2024-11-03 18:00:00,Kavitha,2001-10-25,Female,India,NaN,Cloud Computing,2024-11-03 12:02:17,Rejected,1030,2024-11-01 12:12:41,NaT
3362,2024-04-03 09:44:36,00000000-0GHB-4N83-QX9K-JM48K2,Project Management,Internship,2024-11-03 18:00:00,Maureen,1998-03-12,Female,Nigeria,University of Port Harcourt,NaN,2024-11-03 12:02:17,Rejected,1030,2024-04-03 09:58:15,NaT
4454,2023-06-17 14:59:09,00000000-0GWQ-AXC5-X45C-2MHJ28,Data Visualization,Internship,2024-11-03 18:00:00,VARUN,2002-04-04,Male,India,LOKMANYA TILAK COLLEGE OF ENGINEERING,NaN,2024-11-03 12:02:29,Withdraw,1110,2023-06-17 15:08:46,NaT
4994,2024-04-01 07:08:24,00000000-0GWQ-AXC5-X45C-2MHJ28,Data Visualization,Internship,2024-11-03 18:00:00,Shreevikas,2000-04-08,Male,India,NaN,Computer Science,2024-11-03 12:02:36,Dropped Out,1050,2024-04-01 16:45:40,NaT
4996,2023-09-10 17:16:13,00000000-0GWQ-AXC5-X45C-2MHJ28,Data Visualization,Internship,2024-11-03 18:00:00,Vaishali,1999-01-28,Female,India,Gauhati University,NaN,2024-11-03 12:02:36,Dropped Out,1050,2024-08-01 07:40:35,NaT
6021,2024-09-01 03:21:24,00000000-10GG-17ZM-AP4T-WQVBGQ,Data Visualization Associate,Internship,2024-11-03 18:00:00,Kavitha,2001-10-25,Female,India,NaN,Cloud Computing,2024-11-03 12:02:48,Team Allocated,1070,2024-09-01 03:45:11,NaT

In [42]:
df['Institution Name'] = df['Institution Name'].fillna('Unknown')
df['Current/Intended Major'] = df['Current/Intended Major'].fillna('Unknown')

C:\Users\User\AppData\Local\Temp\ipykernel_13104\501908749.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Institution Name'] = df['Institution Name'].fillna('Unknown')
C:\Users\User\AppData\Local\Temp\ipykernel_13104\501908749.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Current/Intended Major'] = df['Current/Intended Major'].fillna('Unknown')

In [43]:
df.isnull().sum()

Learner SignUp DateTime     295
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1259
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                  307
Opportunity Start Date     4633
dtype: int64

In [44]:
df_copy=df.copy()
df_copy

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,2023-06-14 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Faria,2001-12-01,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,2023-06-14 12:36:09,2022-03-11 18:30:39
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Poojitha,2000-08-16,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Emmanuel,2002-01-27,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,NaT,2022-03-11 18:30:39
3,2023-08-29 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Amrutha Varshini,1999-01-11,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Vinay Varshith,2000-04-19,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Selam,2006-10-14,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,2024-11-03 12:03:14,Team Allocated,1070,2024-05-03 17:10:41,2024-08-03 14:00:00
8554,2024-06-03 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Gowri Sailesh,1999-05-18,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-06-03 18:22:11,2024-08-03 14:00:00
8555,2024-02-29 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Abiola,1999-03-16,Male,Nigeria,Tai Solarin university of Education,Political Science,2024-11-03 12:03:14,Team Allocated,1070,2024-02-29 15:10:06,2024-08-03 14:00:00
8556,2023-12-23 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,venumadhavi,1997-05-06,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-02-27 06:48:47,2024-08-03 14:00:00
8557,2023-01-06 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Prashanth Reddy,2000-11-30,Male,India,Saint Louis University,Artificial Intelligence,2024-11-03 12:03:14,Team Allocated,1070,2024-02-16 16:33:00,2024-08-03 14:00:00

In [45]:
df_copy.isnull().sum()

Learner SignUp DateTime     295
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1259
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                  307
Opportunity Start Date     4633
dtype: int64

In [46]:
df_copy['Learner SignUp DateTime'] = df_copy['Learner SignUp DateTime'].fillna(df_copy['Apply Date'])

df_copy['Apply Date'] = df_copy['Apply Date'].fillna(df_copy['Learner SignUp DateTime'])

In [47]:
df_copy.isnull().sum()

Learner SignUp DateTime      68
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1259
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                   68
Opportunity Start Date     4633
dtype: int64

In [57]:
missing_values=df_copy['Learner SignUp DateTime'].isnull() | df_copy['Apply Date'].isnull()
df_copy[missing_values]

Empty DataFrame
Columns: [Learner SignUp DateTime, Opportunity Id, Opportunity Name, Opportunity Category, Opportunity End Date, First Name, Date of Birth, Gender, Country, Institution Name, Current/Intended Major, Entry created at, Status Description, Status Code, Apply Date, Opportunity Start Date]
Index: []

In [58]:
df_copy[df_copy['Opportunity End Date'].isnull()]['Status Description'].value_counts()

Status Description
Rejected          693
Team Allocated    531
Withdraw           20
Applied             4
Name: count, dtype: int64

In [59]:
#checks whether there are multiple Start Dates for the same project or course name. If the result is 1, it means everything is correct.
# If it is more than 1, it means there is an inconsistency or error there.

grp_by=df_copy.groupby('Opportunity Name')['Opportunity Start Date'].nunique()
grp_by

Opportunity Name
AI Ethics Challenge                                                  0
Business Consulting                                                  0
CPR/AED Certification                                                1
Career Essentials: Getting Started with Your Professional Journey    1
Data Visualization                                                   1
Data Visualization Associate                                         0
Digital Marketing                                                    1
Digital Strategy Virtual Internship                                  0
Freelance Mastery workshop                                           1
Health Care Management                                               1
Innovation & Entrepreneurship                                        1
Join a Student Organisation                                          1
Jump Start: Developing your Emotional Intelligence                   2
Mental and Physical Health Session                                   1
Project Management                                                   1
Project Management Associate                                         0
Slide Geeks: A Presentation Design Competition                       0
Startup Mastery Workshop                                             1
UX Redesign Challenge                                                1
Upload Your First Year Transcript                                    1
UrbanRenew Challenge                                                 1
Xperience Design Hackathon                                           1
Name: Opportunity Start Date, dtype: int64

In [60]:
print(f"Opportunities with multiple start dates: {sum(grp_by > 1)}")

Opportunities with multiple start dates: 1

In [61]:
df_copy['Opportunity Start Date'] = df_copy['Opportunity Start Date'].fillna(
    df.groupby('Opportunity Name')['Opportunity Start Date'].transform('first')
)

print("Remaining missing Start Dates:", df_copy['Opportunity Start Date'].isnull().sum())

Remaining missing Start Dates: 1889

C:\Users\User\AppData\Local\Temp\ipykernel_13104\1673709553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Opportunity Start Date'] = df_copy['Opportunity Start Date'].fillna(

In [62]:
df_copy.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1248
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     1889
dtype: int64

In [63]:
#Fill the missing value from the other row within the same  opportunity group

df_copy['Opportunity Start Date'] = df_copy.groupby('Opportunity Name')['Opportunity Start Date'].transform(lambda x: x.ffill().bfill())

print("Final Missing Start Dates:", df_copy['Opportunity Start Date'].isnull().sum())

Final Missing Start Dates: 1889

C:\Users\User\AppData\Local\Temp\ipykernel_13104\965914578.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Opportunity Start Date'] = df_copy.groupby('Opportunity Name')['Opportunity Start Date'].transform(lambda x: x.ffill().bfill())

In [64]:
df_copy.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1248
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     1889
dtype: int64

In [65]:
df_copy = df_copy.dropna(subset=['Learner SignUp DateTime', 'Apply Date'])

df_copy.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1248
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     1889
dtype: int64

## Feature Engineering
- **New Features Created:**  
  1. `Age` = calculated from Date of Birth  
  2. `Opportunity Duration` = Opportunity End Date - Opportunity Start Date  

- **Rationale:** Age might affect opportunities; duration can show engagement period.

In [66]:
#Now find the ages

df_copy['Age']=df_copy['Apply Date'].dt.year-df_copy['Date of Birth'].dt.year
df_copy['Age'].describe()

count    8472.000000
mean       24.294145
std         4.398932
min         3.000000
25%        22.000000
50%        24.000000
75%        25.000000
max        58.000000
Name: Age, dtype: float64

In [67]:
df_copy[(df_copy['Age']<18) | (df_copy['Age']>100)]

df_copy = df_copy[(df_copy['Age'] >= 18) & (df_copy['Age'] <= 80)]

In [68]:
df_copy['Age'].describe()

count    8241.00000
mean       24.52615
std         4.22505
min        18.00000
25%        22.00000
50%        24.00000
75%        26.00000
max        58.00000
Name: Age, dtype: float64

In [69]:
df_copy.shape

(8241, 17)

In [70]:
df_copy['Country'].unique()

array(['Pakistan', 'India', 'United States', 'Nigeria', 'Egypt', 'Nepal',
       'Kenya', 'Ghana', 'Zambia', 'Morocco', 'Ethiopia', 'Zimbabwe',
       'Uganda', 'Indonesia', 'Cameroon', 'Yemen', 'China', 'Bangladesh',
       'Congo', 'Liberia', 'United Kingdom', 'United Arab Emirates',
       'Vietnam', 'Japan', 'Rwanda', 'Gambia', 'Philippines', 'Australia',
       'Somalia', 'Sierra Leone', 'Lebanon', 'Botswana', 'Iraq', 'Turkey',
       'Honduras', 'Tanzania, United Republic of Tanzania', 'France',
       'Algeria', 'Korea, Republic of South Korea', 'Mauritius',
       'Tunisia', 'Kazakhstan', 'South Africa', 'Germany', 'Namibia',
       'Iran, Islamic Republic of Persian Gulf', 'American Samoa',
       'Falkland Islands (Malvinas)', 'Brazil', 'Dominican Republic',
       'Lesotho', 'Malaysia', 'British Indian Ocean Territory',
       'Virgin Islands, U.S.', 'Qatar', 'Saudi Arabia', 'Canada',
       'Singapore', 'Iran  Islamic Republic of Persian Gulf', 'Ireland',
       'Libyan Arab Jamahiriya', "Cote d'Ivoire", 'Bhutan', 'Ukraine',
       'Spain'], dtype=object)

In [71]:
country_exect_name = {
    'Iran, Islamic Republic of Persian Gulf': 'Iran',
    'Iran  Islamic Republic of Persian Gulf': 'Iran',  # ডুপ্লিকেট ফিক্স
    'Tanzania, United Republic of Tanzania': 'Tanzania',
    'Korea, Republic of South Korea': 'South Korea',
    'Libyan Arab Jamahiriya': 'Libya',
    'Virgin Islands, U.S.': 'US Virgin Islands',
    'Falkland Islands (Malvinas)': 'Falkland Islands'
}

df_copy['Country'] = df_copy['Country'].replace(country_exect_name)

In [72]:
df['Country'].unique()

array(['Pakistan', 'India', 'United States', 'United Arab Emirates',
       'Nigeria', 'Egypt', 'Nepal', 'Kenya', 'Ghana', 'Zambia', 'Morocco',
       'Ethiopia', 'Zimbabwe', 'Uganda', 'Indonesia', 'Cameroon', 'Yemen',
       'China', 'Bangladesh', 'Congo', 'Liberia', 'United Kingdom',
       'Vietnam', 'Japan', 'Rwanda', 'Gambia', 'Philippines', 'Australia',
       'Somalia', 'Sierra Leone', 'Lebanon', 'Botswana', 'Iraq',
       'Uzbekistan', 'Turkey', 'Honduras',
       'Tanzania, United Republic of Tanzania', 'France', 'Belarus',
       'Algeria', 'Korea, Republic of South Korea', 'Mauritius',
       'Tunisia', 'Kazakhstan', 'Peru', 'Brazil', 'Ukraine',
       'South Africa', 'Germany', 'Namibia',
       'Iran, Islamic Republic of Persian Gulf', 'American Samoa',
       'Falkland Islands (Malvinas)', 'Saudi Arabia', 'Sri Lanka',
       'Azerbaijan', 'Dominican Republic', 'Lesotho', 'Malaysia',
       'British Indian Ocean Territory', 'Virgin Islands, U.S.', 'Qatar',
       'Canada', 'Singapore', 'Iran  Islamic Republic of Persian Gulf',
       'Ireland', 'Libyan Arab Jamahiriya', "Cote d'Ivoire",
       'Afghanistan', 'Bhutan', 'Spain'], dtype=object)

In [73]:
df=df_copy.copy()
df

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date,Age
0,2023-06-14 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Faria,2001-12-01,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,2023-06-14 12:36:09,2022-03-11 18:30:39,22
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Poojitha,2000-08-16,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39,23
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Emmanuel,2002-01-27,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,2023-09-04 20:35:08,2022-03-11 18:30:39,21
3,2023-08-29 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Amrutha Varshini,1999-01-11,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39,24
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Vinay Varshith,2000-04-19,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Selam,2006-10-14,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,2024-11-03 12:03:14,Team Allocated,1070,2024-05-03 17:10:41,2024-08-03 14:00:00,18
8554,2024-06-03 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Gowri Sailesh,1999-05-18,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-06-03 18:22:11,2024-08-03 14:00:00,25
8555,2024-02-29 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Abiola,1999-03-16,Male,Nigeria,Tai Solarin university of Education,Political Science,2024-11-03 12:03:14,Team Allocated,1070,2024-02-29 15:10:06,2024-08-03 14:00:00,25
8556,2023-12-23 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,venumadhavi,1997-05-06,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-02-27 06:48:47,2024-08-03 14:00:00,27
8557,2023-01-06 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Prashanth Reddy,2000-11-30,Male,India,Saint Louis University,Artificial Intelligence,2024-11-03 12:03:14,Team Allocated,1070,2024-02-16 16:33:00,2024-08-03 14:00:00,24

In [74]:
df.shape

(8241, 17)

In [75]:
df.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date       1229
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     1870
Age                           0
dtype: int64

In [76]:
missing_opps = df_copy[df_copy['Opportunity Start Date'].isnull()]['Opportunity Name'].unique()
print("Opportunities with all missing Start Dates:", missing_opps)

Opportunities with all missing Start Dates: ['Slide Geeks: A Presentation Design Competition' 'AI Ethics Challenge'
 'Data Visualization Associate' 'Digital Strategy Virtual Internship'
 'Project Management Associate' 'Business Consulting']

In [77]:
durations = df_copy['Opportunity End Date'] - df_copy['Opportunity Start Date']

# Average duration (timedelta)
avg_duration = durations.mean()
print("Average duration:", avg_duration)

Average duration: 321 days 00:44:09.210760740

In [78]:
# Fill missing Opportunity End Dates
df_copy['Opportunity End Date'] = df_copy['Opportunity End Date'].fillna(
    df_copy['Opportunity Start Date'] + pd.Timedelta(days=321)
)

# Verify no missing End Dates left
print("Remaining missing Opportunity End Dates:", df_copy['Opportunity End Date'].isnull().sum())

Remaining missing Opportunity End Dates: 471

In [79]:
# Flag rows where End Date is missing
df_copy['EndDate_missing'] = df_copy['Opportunity End Date'].isnull()

In [80]:
avg_duration_days = 321  # your average duration

df_copy['Opportunity End Date'] = df_copy['Opportunity End Date'].fillna(
    df_copy['Opportunity Start Date'] + pd.Timedelta(days=avg_duration_days)
)

In [82]:
filled_end_dates = df_copy[df_copy['EndDate_missing']][
    ['Opportunity Name', 'Opportunity Start Date', 'Opportunity End Date']
]
filled_end_dates

                  Opportunity Name Opportunity Start Date Opportunity End Date
6802  Project Management Associate                    NaT                  NaT
6803  Project Management Associate                    NaT                  NaT
6804  Project Management Associate                    NaT                  NaT
6805  Project Management Associate                    NaT                  NaT
6806  Project Management Associate                    NaT                  NaT
...                            ...                    ...                  ...
7275  Project Management Associate                    NaT                  NaT
7276  Project Management Associate                    NaT                  NaT
7277  Project Management Associate                    NaT                  NaT
7278  Project Management Associate                    NaT                  NaT
7279  Project Management Associate                    NaT                  NaT

[471 rows x 3 columns]

In [85]:
df_copy.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date        471
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     1870
Age                           0
EndDate_missing               0
dtype: int64

In [86]:
# Average duration in days (from your earlier calculation)
avg_duration_days = 321

# Fill Start Dates where missing
df_copy['Opportunity Start Date'] = df_copy['Opportunity Start Date'].fillna(
    df_copy['Opportunity End Date'] - pd.Timedelta(days=avg_duration_days)
)

# Verify
print("Remaining missing Opportunity Start Dates:", df_copy['Opportunity Start Date'].isnull().sum())

Remaining missing Opportunity Start Dates: 471

In [87]:
# Drop rows where both Start and End Dates are NaN
df_copy = df_copy.dropna(subset=['Opportunity Start Date', 'Opportunity End Date'], how='all')

# Verify
print("Remaining missing Opportunity Start Dates:", df_copy['Opportunity Start Date'].isnull().sum())
print("Remaining missing Opportunity End Dates:", df_copy['Opportunity End Date'].isnull().sum())

Remaining missing Opportunity Start Dates: 0
Remaining missing Opportunity End Dates: 0

In [88]:
df_copy.isnull().sum()

Learner SignUp DateTime    0
Opportunity Id             0
Opportunity Name           0
Opportunity Category       0
Opportunity End Date       0
First Name                 0
Date of Birth              0
Gender                     0
Country                    0
Institution Name           0
Current/Intended Major     0
Entry created at           0
Status Description         0
Status Code                0
Apply Date                 0
Opportunity Start Date     0
Age                        0
EndDate_missing            0
dtype: int64

In [89]:
df_copy

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date,Age,EndDate_missing
0,2023-06-14 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Faria,2001-12-01,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,2023-06-14 12:36:09,2022-03-11 18:30:39,22,False
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Poojitha,2000-08-16,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39,23,False
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Emmanuel,2002-01-27,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,2023-09-04 20:35:08,2022-03-11 18:30:39,21,False
3,2023-08-29 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Amrutha Varshini,1999-01-11,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39,24,False
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Vinay Varshith,2000-04-19,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39,23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Selam,2006-10-14,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,2024-11-03 12:03:14,Team Allocated,1070,2024-05-03 17:10:41,2024-08-03 14:00:00,18,False
8554,2024-06-03 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Gowri Sailesh,1999-05-18,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-06-03 18:22:11,2024-08-03 14:00:00,25,False
8555,2024-02-29 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Abiola,1999-03-16,Male,Nigeria,Tai Solarin university of Education,Political Science,2024-11-03 12:03:14,Team Allocated,1070,2024-02-29 15:10:06,2024-08-03 14:00:00,25,False
8556,2023-12-23 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,venumadhavi,1997-05-06,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-02-27 06:48:47,2024-08-03 14:00:00,27,False
8557,2023-01-06 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Prashanth Reddy,2000-11-30,Male,India,Saint Louis University,Artificial Intelligence,2024-11-03 12:03:14,Team Allocated,1070,2024-02-16 16:33:00,2024-08-03 14:00:00,24,False

## Data Validation
- Checked for negative ages or durations
- Verified no missing values remain in key columns
- Confirmed duplicates removed

In [90]:
# Check for remaining nulls
df_copy[['Opportunity Start Date', 'Opportunity End Date']].isnull().sum()

Opportunity Start Date    0
Opportunity End Date      0
dtype: int64

In [92]:
df_copy = df_copy.drop(columns=['EndDate_missing'])

In [93]:
df_copy.columns

Index(['Learner SignUp DateTime', 'Opportunity Id', 'Opportunity Name',
       'Opportunity Category', 'Opportunity End Date', 'First Name',
       'Date of Birth', 'Gender', 'Country', 'Institution Name',
       'Current/Intended Major', 'Entry created at', 'Status Description',
       'Status Code', 'Apply Date', 'Opportunity Start Date', 'Age'],
      dtype='object')

In [96]:
df_copy

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date,Age
0,2023-06-14 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Faria,2001-12-01,Female,Pakistan,Nwihs,Radiology,2024-11-03 12:01:41,Started,1080,2023-06-14 12:36:09,2022-03-11 18:30:39,22
1,2023-01-05 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Poojitha,2000-08-16,Female,India,SAINT LOUIS,Information Systems,2024-11-03 12:01:41,Started,1080,2023-01-05 06:08:21,2022-03-11 18:30:39,23
2,2023-09-04 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Emmanuel,2002-01-27,Male,United States,Illinois Institute of Technology,Computer Science,2024-11-03 12:01:41,Started,1080,2023-09-04 20:35:08,2022-03-11 18:30:39,21
3,2023-08-29 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Amrutha Varshini,1999-01-11,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:01:41,Team Allocated,1070,2023-09-10 22:02:42,2022-03-11 18:30:39,24
4,2023-06-01 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29 18:52:39,Vinay Varshith,2000-04-19,Male,United States,Saint Louis University,Computer Science,2024-11-03 12:01:41,Started,1080,2023-06-01 15:40:10,2022-03-11 18:30:39,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,2024-05-03 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Selam,2006-10-14,Female,Ethiopia,Lideta Catholic Cathedral School,Computer Science,2024-11-03 12:03:14,Team Allocated,1070,2024-05-03 17:10:41,2024-08-03 14:00:00,18
8554,2024-06-03 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Gowri Sailesh,1999-05-18,Male,United States,SAINT LOUIS UNIVERSITY,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-06-03 18:22:11,2024-08-03 14:00:00,25
8555,2024-02-29 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Abiola,1999-03-16,Male,Nigeria,Tai Solarin university of Education,Political Science,2024-11-03 12:03:14,Team Allocated,1070,2024-02-29 15:10:06,2024-08-03 14:00:00,25
8556,2023-12-23 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,venumadhavi,1997-05-06,Female,United States,Saint Louis University,Information Systems,2024-11-03 12:03:14,Team Allocated,1070,2024-02-27 06:48:47,2024-08-03 14:00:00,27
8557,2023-01-06 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,2024-08-03 11:30:00,Prashanth Reddy,2000-11-30,Male,India,Saint Louis University,Artificial Intelligence,2024-11-03 12:03:14,Team Allocated,1070,2024-02-16 16:33:00,2024-08-03 14:00:00,24

In [98]:
df = df_copy

In [99]:
df.to_excel('Cleaned_Preprocessed_SLU_Opportunity_Dataset_Week1_df.xlsx', index=False)

print("Excel File made successfully")

Excel File made successfully

## Overview
The workflow began with standardizing all datetime fields to a consistent datetime format to ensure accuracy and enable reliable time-based operations.

An initial assessment of missing values was then performed across all columns to identify data quality issues and guide subsequent cleaning decisions. Particular attention was given to the Opportunity Start Date and Opportunity End Date fields due to their importance for temporal analysis. Where one of these dates was missing, the absent value was logically estimated using the average opportunity duration calculated from records with complete date information. Records lacking both start and end dates were removed, as no meaningful temporal inference could be made.

In addition to date handling, feature engineering was applied to derive an Age column from the learners’ dates of birth. This transformation enabled age-based analysis while preserving the original birth date information.

Final validation checks confirmed that all critical fields were complete, date ranges were consistent, and the dataset was fully prepared for downstream analysis, visualization, and reporting.